"""update users table - new schema

Revision ID: baadbab55ef1
Revises: f72ac1c61b4c
Create Date: 2026-08-21 20:35:54.221276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'baadbab55ef1'
down_revision = 'f72ac1c61b4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=150), nullable=False))
        batch_op.add_column(sa.Column('profile', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('role', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('shift')
        batch_op.drop_column('username')
        batch_op.drop_column('branch_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('branch_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=120), nullable=False))
        batch_op.add_column(sa.Column('shift', sa.VARCHAR(length=50), nullable=False))
        batch_op.create_foreign_key(None, 'branches', ['branch_id'], ['id'])
        batch_op.alter_column('password',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
        batch_op.drop_column('created_at')
        batch_op.drop_column('role')
        batch_op.drop_column('profile')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
